name: Windows-CRD

on:
  repository_dispatch:
    types: [start]

  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Install Webcam Driver
      run: ./webcam.ps1
    - name: Starting Livestream
      run: ./start-stream.ps1
    - name: Keep Alive
      run: ./timeout.ps1
